{{- if .Values.certManager.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    {{- include "wardianapp.labels" . | nindent 4 }}
spec:
  acme:
    server: {{ .Values.certManager.server }}
    email: {{ .Values.certManager.email }}
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-key
            key: api-token
{{- end }}
