apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wardianapp.fullname" . }}-config
  labels:
    {{- include "wardianapp.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.app.env | quote }}
  APP_DEBUG: {{ .Values.app.debug | quote }}
