apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wardianapp.fullname" . }}-secrets
  labels:
    {{- include "wardianapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  SYMFONY_DECRYPTION_SECRET: {{ .Values.secrets.symfonyDecryptionSecret | quote }}
